default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
        stages: [commit]
      # Check merge conflict is not applied during rebase (no commit is done) so the issue can still be pushed
      - id: check-merge-conflict
        args:
            - --assume-in-merge
        stages: [push]
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [scala]
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
